apiVersion: v1
kind: Service
metadata:
  name: light-proxy-service
spec:
  selector:
    app: light-proxy
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 32000
      port: 8080
      targetPort: 8080