apiVersion: v1
kind: Service
metadata:
   name: light-proxy-service
   labels:
     app: light-proxy
spec:
  selector:
    app: light-proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 80